-- ===========================================
-- CLINICAL MANAGEMENT (OPD, IPD, ICU, OT)
-- ===========================================

-- OPD Records
CREATE TABLE opd_records (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    doctor_id BIGINT UNSIGNED NOT NULL,
    visit_id BIGINT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED,
    opd_id VARCHAR(50) UNIQUE NOT NULL,
    opd_date DATE NOT NULL,
    opd_time TIME NOT NULL,
    chief_complaint TEXT,
    history_presenting TEXT,
    past_history TEXT,
    personal_history TEXT,
    family_history TEXT,
    treatment_history TEXT,
    vitals JSON,
    physical_examination TEXT,
    provisional_diagnosis TEXT,
    final_diagnosis TEXT,
    investigation_advised TEXT,
    treatment_advised TEXT,
    advice TEXT,
    follow_up_date DATE,
    referral_notes TEXT,
    status ENUM('draft', 'final', 'cancelled') DEFAULT 'draft',
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (doctor_id) REFERENCES users(id),
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- IPD Records
CREATE TABLE ipd_records (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    admission_id BIGINT UNSIGNED NOT NULL,
    bed_id BIGINT UNSIGNED NOT NULL,
    doctor_id BIGINT UNSIGNED NOT NULL,
    ipd_id VARCHAR(50) UNIQUE NOT NULL,
    ipd_date DATE NOT NULL,
    ipd_time TIME NOT NULL,
    diagnosis TEXT,
    treatment_plan TEXT,
    day_number INT DEFAULT 1,
    vitals JSON,
    input_output JSON,
    fluids_iv TEXT,
    medications TEXT,
    diet_advice TEXT,
    nursing_notes TEXT,
    doctor_notes TEXT,
    is_icu BOOLEAN DEFAULT FALSE,
    status ENUM('active', 'discharged', 'transferred') DEFAULT 'active',
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (admission_id) REFERENCES patient_admissions(id),
    FOREIGN KEY (bed_id) REFERENCES beds(id),
    FOREIGN KEY (doctor_id) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Nursing Records
CREATE TABLE nursing_records (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    admission_id BIGINT UNSIGNED NOT NULL,
    nurse_id BIGINT UNSIGNED NOT NULL,
    record_id VARCHAR(50) UNIQUE NOT NULL,
    record_date DATE NOT NULL,
    record_time TIME NOT NULL,
    shift ENUM('morning', 'evening', 'night') DEFAULT 'morning',
    vitals JSON,
    input_output JSON,
    medications_given TEXT,
    procedures_done TEXT,
    observations TEXT,
    complications TEXT,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (admission_id) REFERENCES patient_admissions(id),
    FOREIGN KEY (nurse_id) REFERENCES users(id)
);

-- ICU Records
CREATE TABLE icu_records (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    admission_id BIGINT UNSIGNED NOT NULL,
    doctor_id BIGINT UNSIGNED NOT NULL,
    icu_id VARCHAR(50) UNIQUE NOT NULL,
    icu_date DATE NOT NULL,
    icu_time TIME NOT NULL,
    vitals JSON,
    consciousness_level VARCHAR(50),
    respirator_settings JSON,
    oxygen_saturation DECIMAL(5,2),
    ventilator_mode VARCHAR(50),
    iv_fluids TEXT,
    medications TEXT,
    lab_results TEXT,
    doctor_notes TEXT,
    emergency_notes TEXT,
    status ENUM('active', 'stable', 'critical', 'transferred', 'discharged') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (admission_id) REFERENCES patient_admissions(id),
    FOREIGN KEY (doctor_id) REFERENCES users(id)
);

-- Operation Theatre (OT) Schedules
CREATE TABLE ot_schedules (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    doctor_id BIGINT UNSIGNED NOT NULL,
    assistant_doctor_id BIGINT UNSIGNED,
    anesthetist_id BIGINT UNSIGNED,
    nurse_id BIGINT UNSIGNED,
    ot_id VARCHAR(50) UNIQUE NOT NULL,
    ot_number VARCHAR(20) NOT NULL,
    surgery_date DATE NOT NULL,
    surgery_time TIME NOT NULL,
    expected_duration INT DEFAULT 60,
    surgery_type VARCHAR(255),
    surgery_reason TEXT,
    pre_operation_notes TEXT,
    post_operation_notes TEXT,
    anesthesia_type VARCHAR(100),
    status ENUM('scheduled', 'prepared', 'in_progress', 'completed', 'cancelled', 'postponed') DEFAULT 'scheduled',
    is_emergency BOOLEAN DEFAULT FALSE,
    priority ENUM('routine', 'urgent', 'emergency') DEFAULT 'routine',
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (doctor_id) REFERENCES users(id),
    FOREIGN KEY (assistant_doctor_id) REFERENCES users(id),
    FOREIGN KEY (anesthetist_id) REFERENCES users(id),
    FOREIGN KEY (nurse_id) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);