-- ===========================================
-- BILLING & ACCOUNTING MODULE
-- ===========================================

-- Chart of Accounts (Hospital Specific)
CREATE TABLE chart_of_accounts (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    account_code VARCHAR(20) UNIQUE NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    group_code VARCHAR(20) NOT NULL,
    head_code VARCHAR(20) NOT NULL,
    account_type ENUM('debit', 'credit') NOT NULL,
    opening_balance DECIMAL(15,2) DEFAULT 0,
    opening_balance_date DATE,
    current_balance DECIMAL(15,2) DEFAULT 0,
    status ENUM('active', 'inactive') DEFAULT 'active',
    is_default BOOLEAN DEFAULT FALSE,
    is_system BOOLEAN DEFAULT FALSE,
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Hospital Billing
CREATE TABLE hospital_bills (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    admission_id BIGINT UNSIGNED,
    visit_id BIGINT UNSIGNED,
    bill_id VARCHAR(50) UNIQUE NOT NULL,
    bill_date DATE NOT NULL,
    bill_time TIME NOT NULL,
    bill_type ENUM('opd', 'ipd', 'emergency', 'pharmacy', 'lab', 'radiology', 'procedure', 'discharge') DEFAULT 'opd',
    subtotal DECIMAL(15,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    tax_amount DECIMAL(15,2) DEFAULT 0,
    service_charge DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) DEFAULT 0,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    balance_amount DECIMAL(15,2) DEFAULT 0,
    payment_status ENUM('pending', 'partial', 'paid', 'overdue', 'written_off') DEFAULT 'pending',
    insurance_claim_amount DECIMAL(15,2) DEFAULT 0,
    tpa_claim_amount DECIMAL(15,2) DEFAULT 0,
    patient_payable DECIMAL(15,2) DEFAULT 0,
    due_date DATE,
    notes TEXT,
    voucher_id BIGINT UNSIGNED,
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (admission_id) REFERENCES patient_admissions(id) ON DELETE SET NULL,
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id) ON DELETE SET NULL,
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Bill Items
CREATE TABLE bill_items (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    bill_id BIGINT UNSIGNED NOT NULL,
    item_type VARCHAR(50) NOT NULL,
    item_id BIGINT UNSIGNED,
    description VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 1,
    unit_price DECIMAL(15,2) NOT NULL,
    discount_percent DECIMAL(5,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    gst_rate DECIMAL(5,2) DEFAULT 0,
    gst_amount DECIMAL(15,2) DEFAULT 0,
    total DECIMAL(15,2) NOT NULL,
    reference_no VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bill_id) REFERENCES hospital_bills(id) ON DELETE CASCADE
);

-- Insurance Claims
CREATE TABLE insurance_claims (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    admission_id BIGINT UNSIGNED,
    bill_id BIGINT UNSIGNED,
    claim_id VARCHAR(50) UNIQUE NOT NULL,
    claim_date DATE NOT NULL,
    insurance_provider VARCHAR(255) NOT NULL,
    policy_number VARCHAR(50),
    tpa_name VARCHAR(255),
    claim_amount DECIMAL(15,2) DEFAULT 0,
    approved_amount DECIMAL(15,2) DEFAULT 0,
    rejected_amount DECIMAL(15,2) DEFAULT 0,
    claim_status ENUM('draft', 'submitted', 'under_review', 'approved', 'rejected', 'settled') DEFAULT 'draft',
    submission_date DATE,
    approval_date DATE,
    settlement_date DATE,
    rejection_reason TEXT,
    documents JSON,
    notes TEXT,
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (admission_id) REFERENCES patient_admissions(id) ON DELETE SET NULL,
    FOREIGN KEY (bill_id) REFERENCES hospital_bills(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Payments
CREATE TABLE hospital_payments (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    hospital_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    bill_id BIGINT UNSIGNED NOT NULL,
    payment_id VARCHAR(50) UNIQUE NOT NULL,
    payment_date DATE NOT NULL,
    payment_time TIME NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    payment_method ENUM('cash', 'card', 'upi', 'insurance', 'tpa', 'cheque', 'bank_transfer') DEFAULT 'cash',
    transaction_id VARCHAR(255),
    card_last_four VARCHAR(4),
    cheque_number VARCHAR(50),
    cheque_date DATE,
    bank_name VARCHAR(255),
    upi_id VARCHAR(100),
    payment_reference VARCHAR(255),
    status ENUM('pending', 'success', 'failed', 'refunded') DEFAULT 'success',
    gateway_response JSON,
    received_by BIGINT UNSIGNED,
    voucher_id BIGINT UNSIGNED,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (bill_id) REFERENCES hospital_bills(id),
    FOREIGN KEY (received_by) REFERENCES users(id),
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL
);

-- Daybook (Double-Entry Ledger)
CREATE TABLE daybook (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    slno BIGINT UNSIGNED AUTO_INCREMENT UNIQUE,
    sno BIGINT UNSIGNED NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    opposite_account_code VARCHAR(20) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    drcr ENUM('dr', 'cr') NOT NULL,
    voucher_type ENUM('billing', 'payment', 'receipt', 'journal', 'contra', 'insurance') NOT NULL,
    voucher_no VARCHAR(50) NOT NULL,
    voucher_date DATE NOT NULL,
    remarks TEXT,
    reference_no VARCHAR(50),
    reference_date DATE,
    patient_id BIGINT UNSIGNED,
    bill_id BIGINT UNSIGNED,
    hospital_id BIGINT UNSIGNED,
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (account_code) REFERENCES chart_of_accounts(account_code),
    FOREIGN KEY (opposite_account_code) REFERENCES chart_of_accounts(account_code),
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE SET NULL,
    FOREIGN KEY (bill_id) REFERENCES hospital_bills(id) ON DELETE SET NULL,
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_voucher (voucher_type, voucher_no),
    INDEX idx_account (account_code)
);

-- Vouchers
CREATE TABLE vouchers (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    voucher_no VARCHAR(50) NOT NULL,
    voucher_type ENUM('billing', 'payment', 'receipt', 'journal', 'contra', 'insurance') NOT NULL,
    voucher_date DATE NOT NULL,
    reference_no VARCHAR(50),
    reference_date DATE,
    narration TEXT,
    total_debit DECIMAL(15,2) DEFAULT 0,
    total_credit DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) DEFAULT 0,
    balance_difference DECIMAL(15,2) DEFAULT 0,
    is_balanced BOOLEAN DEFAULT FALSE,
    is_posted BOOLEAN DEFAULT FALSE,
    posted_by BIGINT UNSIGNED,
    posted_at TIMESTAMP NULL,
    hospital_id BIGINT UNSIGNED,
    created_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (posted_by) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE SET NULL,
    UNIQUE KEY unique_voucher (company_id, voucher_type, voucher_no)
);